trigger:
- master
- development
- preprod
- hotfix
- feature/*
- dev/*
- design/*

pool:
  vmImage: windows-latest

steps:
- bash: |
    git push --prune https://$(githubpersonaltoken)@github.com/thibaultmaudet/Covid19Dashboard.git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'